# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI



on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Ivan
        - name: Log Greeting Time
           run: echo "${{ steps.greet.outputs.time } }"

#    - name: Update server on remote instance
#      uses:  fifsky/ssh-action@master
#      with:
#        host: ${{ secrets.EC2_SSH_HOST }}
#        user: ${{ secrets.EC2_SSH_USER }}
#        key: ${{ secrets.SSH_KEY }}
#        command: |
#            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v14.19.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
#            cd ~/test-ci-cd
#            echo "Kill all the running PM2 actions"
#            pm2 kill
#
#            echo "Stash changes"
#            git stash
#
#            echo "Pull updates"
#            git pull origin main
#
#            echo "Check node version"
#            node -v
#            echo "Install app dependencies"
#            rm -rf node_modules
#            npm install
#            pm2 start "npm start" --name server
#            # echo "Print current env"
#            # printenv

