# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: sh ../scripts/deploy.sh
#  restart-server:
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: AWS SSM Send-Command
#        uses: peterkimzz/aws-ssm-send-command@master
#        id: ssm
#        with:
#          aws-region: ${{ secrets.AWS_REGION }}
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          instance-ids: ${{ secrets.INSTANCE_ID }}
#
#          working-directory: ~/test-ci-cd
#          command: touch hello-world.txt
#          comment: Hello world!
