# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          user: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          connect_timeout: 10s
          script: sh ./.github/scripts/restart-updated-server.sh
