# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update server on remote instance
      uses:  fifsky/ssh-action@master
      with:
        host: ${{ secrets.EC2_SSH_HOST }}
        user: ${{ secrets.EC2_SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        command: |
            ls
            cd ~/test-ci-cd
            pwd
            ./.github/scripts/restart-updated-server.sh 
    # - name: executing remote ssh commands using ssh key
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_SSH_HOST }}
    #     username: ${{ secrets.EC2_SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       node -v
    #       ls
    # - name: SSH remote run
    #   uses: Boberneprotiv/ssh-remove-run@v1
    #   with: 
    #       private-key-path: ${{ secrets.SSH_KEY  }}
    #       host : ${{ secrets.EC2_SSH_HOST  }}
    #       user : ${{ secrets.EC2_SSH_USER  }}
    #       run: |
    #         node -v
    #         ls

      # - uses: actions/checkout@v2 
      # - name: Deploy in EC2
      #   env:
      #       PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
      #       HOSTNAME : ${{ secrets.EC2_SSH_HOST  }}
      #       USER_NAME : ${{ secrets.EC2_SSH_USER  }}
            
      #   run: |
      #     cd /home/ubuntu/test-ci-cd/
      #     node -v
      #     ls
      #     npm i
      #     pwd