# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: Boberneprotiv/ssh-remove-run@v1
    - name: SSH remote run
      with: 
          private-key-path: ${{ secrets.SSH_KEY  }}
          host : ${{ secrets.EC2_SSH_HOST  }}
          user : ${{ secrets.EC2_SSH_USER  }}
          run: |
            node -v
            ls

      # - uses: actions/checkout@v2 
      # - name: Deploy in EC2
      #   env:
      #       PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
      #       HOSTNAME : ${{ secrets.EC2_SSH_HOST  }}
      #       USER_NAME : ${{ secrets.EC2_SSH_USER  }}
            
      #   run: |
      #     cd /home/ubuntu/test-ci-cd/
      #     node -v
      #     ls
      #     npm i
      #     pwd